# Generated by Django 6.0.6 on 2026-06-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passengerprofile'),
        ('companies', '0002_rename_name_city_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.transportcompany'),
        ),
    ]
