# Generated by Django 6.0.6 on 2026-06-06 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.PositiveIntegerField()),
                ('trip_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=20)),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_trips', to='companies.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.transportcompany')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_trips', to='companies.city')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.vehicle')),
            ],
        ),
    ]
