# Generated by Django 6.0.6 on 2026-08-10 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_name_city_city_name'),
        ('trips', '0002_remove_trip_arrival_city_remove_trip_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='companies.transportcompany'),
        ),
    ]
